### PR TITLE
Update to latest golang patch.

### PR DESCRIPTION
**Pull request by ScheererJ**
**What this PR does / why we need it**:
Update to latest golang patch.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Release note**:

```feature user

```

### CODE REVIEW

**Review by MartinWeindel — APPROVED** [review]
/lgtm

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Comment by DockToFuture** [comment]
Can you also update https://github.com/gardener/aws-custom-route-controller/blob/main/.ci/pipeline_definitions#L21

**Comment by ScheererJ** [comment]
> Can you also update https://github.com/gardener/aws-custom-route-controller/blob/main/.ci/pipeline_definitions#L21

Good catch. Updated as requested.

**Pull request merged**
